[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "postura_pose"
version = "0.1.0"
description = "MediaPipe pose detection component for Postura"
requires-python = ">=3.9"
dependencies = [
    "streamlit>=1.53",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["postura_pose*"]

[tool.setuptools.package-data]
"postura_pose" = [
    "frontend/build/*",
    "pyproject.toml",
]

[[tool.streamlit.component.components]]
name = "postura_pose"
asset_dir = "frontend/build"